index:
    path: /
    controller: App\Controller\IndexController::index


file:
    path: /new
    controller: App\Controller\IndexController::validateFile
    methods: POST

gen:
    path: /gen/{file}
    controller: App\Controller\IndexController::showFile
    methods: GET
    requirements:
        file: '.+'

generate:
    path: /gen/{file}
    controller: App\Controller\IndexController::generateFile
    methods: POST
    requirements:
        file: '.+'

