index:
    path: /
    controller: App\Controller\IndexController::index

gen:
    path: /gen/{file}
    controller: App\Controller\IndexController::f

file:
    path: /file
    controller: App\Controller\IndexController::ff

